### ISSUE TITLE
Add --dump option to show contents of .metadata file

### ISSUE THREAD

**Issue by dfandrich** [przemoc/metastore#13]
A --dump option that dumps the contents of the .metadata file in a format similar to ls -l would be very useful in debugging and troubleshooting merge problems, et. al.

**Comment by przemoc** [comment]
You have a point here. I think I'm ok with it on second thought.

I'll prepare enhancement entry next week. One thing that needs to remain clear is that this dump should be aimed only at human consumption, i.e. nothing that some scripts would depend on, as it would lock us down later unpleasantly. Mind also that `ls -l` lacks details related to xattr, but beside that it should be mostly fine. Actually I would prefer to base it on following output:

    ls -alp --time-style=full-iso

with some xattr related improvements (don't have anything particular on my mind yet regarding it).

**Comment by przemoc** [comment]
Request accepted. Follow-up in #28.
