### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by vitlav** [przemoc/metastore#25]
Please, make a new release for metastore in some short time. It is very useful for program packaging when a program has releases numbers.

**Comment by przemoc** [comment]
Yes, metastore is planned to be released before the end of next month. I just didn't have time lately to focus on it. I still have to do a few things and set up some "infrastracture" before metastore 1.1 going live. Sorry for the inconvenience that lack of official release may be causing you.

**Comment by przemoc** [comment]
I had to postpone it last month, but this month will definitely see metastore v1.1 finally released.

**Comment by przemoc** [comment]
I assumed that David Härdeman (original metastore author) will perform the actions I mailed to him within this month, but I think I was overly optimistic. Sorry for that. Clearing #16 is _conditio sine qua non_ to even think about tagging and officially releasing new version.

**Comment by przemoc** [comment]
Main showstopper is finally cleared, i.e. this repo became the official one. Unfortunately I'm a bit busy lately, so v1.1.0 rather won't be released this week, but November will see new metastore at last. No ifs, ands, or buts!

**Comment by przemoc** [comment]
I'm a bit behind schedule, because end of October brought something I could not anticipate, changing my November plans considerably. Life learned me again that you cannot have absolute plans and be sure of anything...

But I should be more or less on track now.

**Comment by przemoc** [comment]
metastore is getting into shape.

FTP/HTTP seems to be ready. I've created my PGP key [0x879C7468EAD49C84][1] last year and got 2 sigs recently.  I still have to rewrite Makefile and some mail with (short) release notes has to be drafted.

Such mail should have obvious `To:` header, but there is no such place yet. metastore should have its own mailing list, at least for release announcements, but I cannot find any free and decent solution, that would not enforce me to host it myself. [librelist][2] goes against all standards with its wacky subscription mechanism. [Google Groups][3] doesn't seem to be any better... 

  [1]: https://sks-keyservers.net/pks/lookup?op=vindex&search=0x879C7468EAD49C84
  [2]: http://librelist.com/
  [3]: https://groups.google.com/

**Comment by przemoc** [comment]
So I created read-only mailing list for announcements in [FreeLists](https://www.freelists.org/) service: Details are in the README already.

I'm not sure yet, whether it was a good decision, because Gmane (which I like a lot) cannot archive it. I learned about it ~3 hours ago from one of Gmane admins:
> Sorry, freelists.org does not want any of their mailing lists on Gmane.

Let's live with it for now.

**Comment by przemoc** [comment]
I sent a first non-release mail to the mailing list:
https://www.freelists.org/post/metastore-announce/metastore-a-bit-of-history

The next mail on metastore-announce, which should be sent within ~24 hours, will be about the new version of metastore. Last commit(s) and tag v1.1.0 will not show up before Monday (it's already Monday in Poland - quarter after midnight), as I wrote in the mail, but on Monday (in CET timezone), i.e. today.

**Comment by przemoc** [comment]
https://www.freelists.org/post/metastore-announce/metastore-v110

**Comment by przemoc** [comment]
https://www.freelists.org/post/metastore-announce/metastore-v110,1
