### ISSUE TITLE
Fails to build on Arch Linux

### ISSUE THREAD

**Issue by edacval** [przemoc/metastore#29]
Error:
~~~
gcc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -g -Wall -pedantic -std=c99 -D_FILE_OFFSET_BITS=64 -O2 -Wl,-O1,--sort-common,--as-needed,-z,relro -lbsd -o metastore utils.o metastore.o metaentry.o
metaentry.o: In function `mentries_dump':
~/metastore/metaentry.c:643: undefined reference to `strmode'
~~~

This was caused by the default `LDFLAGS="-Wl,--as-needed"` on Arch Linux, Gentoo and, guess, many other modern distributions.

According to https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed#Importance_of_linking_order, libraries must be passed to linker after the object files and the static archives.

**Comment by przemoc** [comment]
Thanks for the report. The fix has been pushed.
