### ISSUE TITLE
Branches switching support

### ISSUE THREAD

**Issue by vtolstov** [przemoc/metastore#3]
currenct metastore hooks does not support branches that contains different dirs/files perms.

**Comment by przemoc** [comment]
I believe that the matter has been fixed for some time (to the extent that git hooks allow). Just now I only improved it further a little (in 95921e7ad884). Please check a warning in the comments of [pre-commit](https://github.com/przemoc/metastore/blob/master/examples/hooks/pre-commit) hook, though. 

@vtolstov Please check how the hook scripts work for you now.
