### ISSUE TITLE
Change default installation prefix to /usr/local

### ISSUE THREAD

**Issue by krichter722** [przemoc/metastore#34]
since it messes up binaries installed by package management (e.g. on Debian based systems). Either the prefix should be `/usr/local` or - even better - configurable.

Consider switching to `autoconf` which might seem overkill, but avoids creating a `configure` script now which later will be replaced by `autoconf` anyway or always consume maintenance costs.

When switching to `autoconf` #23 has to be reviewed.

**Comment by przemoc** [comment]
Rewritten Makefile (#23) will have `/usr/local` as default PREFIX, which will be obviously alterable (`make install PREFIX=/usr` etc.).

I'm against autohell, though. So sorry, but as long as I'm metastore maintainer, `autoconf` won't be used in metastore.
