### ISSUE TITLE
Can't change owner when current owner is numeric UID

### ISSUE THREAD

**Issue by microchip** [przemoc/metastore#41]
Attempting to apply metadata to a filesystem where the current UID/GID is not in /etc/passwd results in a "getpwuid failed" error on startup, and a failure to change the ownership of the files specified in .metadata, with a "removed" message when the files were actually there.

(Situation occurred after running an rsync from a host when restoring, and the UID/GID in question restored by rsync was a different UID/GID to the original.)

**Comment by przemoc** [comment]
It's symmetric to issue: #37.
Fixing it sensibly requires some other stuff, which isn't in metastore yet.

**Comment by microchip** [comment]
Sorry, hadn't registered that previous bug when I looked through. Will close this bug and add notes to #37 .
