### ISSUE TITLE
Do not skip nanoseconds when applying mtime

### ISSUE THREAD

**Issue by bjohas** [przemoc/metastore#64]
Hello!

Using this tool with git, for synchronising a set of files where I'd like to preserve timestamps!

It seems that metastore creates the .metastore with nanoseconds, but during application only applies the timestamp to the nearest second. Therefore, when synchronising back/forth, the nanoseconds are eliminated.

Could the tool be adjusted so that there's a choice over seconds vs. fractional seconds?

**Comment by przemoc** [comment]
Thank you, @bjohas, for reporting this bug. It has been fixed with latest push (commit a20cb5571cf8). I will appreciate testing and confirming it on your side.
